config/routes.rb
Rails.application.routes.draw do
	get 'welcome/index'
	
	resources :tasks
	
	root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def new
	end
	
	def create
	  @task = Task.new(task_params)
	 
	  @task.save
	  redirect_to @task
	end
	def index
		@tasks = Task.all
	end
	 
	def show
	@task = Task.find(params[:id])
	end
	
	private
		def task_params
			params.require(:task).permit(:title, :description, :done)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
	<th>Done</th>
    <th></th>
  </tr>
 
  <% @tasks.each do |task| %>
    <tr>
      <td><%= task.title %></td>
      <td><%= task.description %></td>
	  <td><%= task.done %></td>
      <td><%= link_to 'Show', task_path(task) %></td>
    </tr>
  <% end %>
</table>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_with scope: :task, url: tasks_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>
  
  <p>
    <%= form.label :done %><br>
    <%= form.check_box :done %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/tasks/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Done:</strong>
  <%= @task.done %>
</p>